### ISSUE TITLE
Сделайте паблик, плиз, у кого права)

### ISSUE THREAD

**Issue by PlagaMedicum** [iit-students-charity/monkey#1]

**Comment by PlagaMedicum** [comment]
сделал трансфер репы и потерял права на редактирование. @ARtoriouSs можешь, плиз, сделать паблик?)

**Comment by ARtoriouSs** [comment]
@PlagaMedicum готово)

**Comment by PlagaMedicum** [comment]
@ARtoriouSs дзякуй!)
